"""kb_document.source_conversation_id

Revision ID: 4563f8ba71f0
Revises: d4b051fbb517
Create Date: 2026-07-15 19:54:22.195678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4563f8ba71f0'
down_revision: Union[str, Sequence[str], None] = 'd4b051fbb517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_conversation_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_kb_document_source_conversation_id'), ['source_conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_document_source_conversation_id'))
        batch_op.drop_column('source_conversation_id')

    # ### end Alembic commands ###
