"""wecom_config

Revision ID: 5e998459561d
Revises: 8b87d870a0e6
Create Date: 2026-07-13 20:03:43.822456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e998459561d'
down_revision: Union[str, Sequence[str], None] = '8b87d870a0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wecom_config',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('corp_id', sa.String(length=64), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.Column('callback_token', sa.String(length=64), nullable=False),
    sa.Column('aeskey_enc', sa.Text(), nullable=False),
    sa.Column('open_kfid', sa.String(length=64), nullable=False),
    sa.Column('sync_cursor', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wecom_config')
    # ### end Alembic commands ###
