"""add kb_chunk

Revision ID: 8b87d870a0e6
Revises: f02036d320e5
Create Date: 2026-07-08 18:21:35.205946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b87d870a0e6'
down_revision: Union[str, Sequence[str], None] = 'f02036d320e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['kb_document.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_chunk_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_chunk_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_chunk_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_kb_chunk_document_id'))

    op.drop_table('kb_chunk')
    # ### end Alembic commands ###
